# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: build
build: ## Build the docker image.
	docker build -f Dockerfile . -t search-operator-bundle
