name: Update Search V2 operator bundle image versions

# Set jobs to be configured and executed by schedule.
on:
  schedule:
    - cron: '0 0,22 * * 1-5' # Actions will be executed at 8am for every weekday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run script for bundle image pickup
        id: image-pickup
        run: |
          bash ./scripts/bundle-image-pickup.sh -s

      - name: Add updated log report to CHANGELOG
        run: |
          echo -e "\nGenerated auto update. View Github Action: [${{ github.run_id }}](https://github.com/stolostron/search-v2-operator-bundle/actions/runs/${{ github.run_id }})" >> CHANGELOG.md

      - name: Create pull request for updated bundle image versions
        if: steps.image-pickup.outcome == 'success'
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: |
            CHANGELOG.md
            bundle/manifests/search-v2-operator.clusterserviceversion.yaml
          body: |
            This PR is auto-generated by the Git action [bundle-image-update](https://github.com/stolostron/search-v2-operator-bundle/blob/main/.github/workflows/bundle-image-update.yml).
          branch-suffix: short-commit-hash
          commit-message: 'Updated bundle image versions within the project'
          delete-branch: true
          labels: automated-pr
          reviewers: |
            dislbenn
            jlpadilla
            xrajesh
          signoff: true
          title: '[Automated PR] Updated bundle image versions within the project'
          token: ${{ secrets.GITHUB_TOKEN }}