name: Update Search V2 operator bundle image versions

# Set jobs to be configured and executed by schedule.
on:
  # push:
  #   branches:
  #     - 'main'
  #     - 'release-2.7'
  schedule:
    - cron: '0 6 * * 1-5' # Actions will be executed at 6am for every weekday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create log entry for github action results
        run: |
          mkdir -p .github/logs
          echo -e "### Generated logs from GitHub Action: [${{ github.run_id }}](https://github.com/stolostron/search-v2-operator-bundle/actions/runs/${{ github.run_id }})" >> .github/logs/update-log-$(date +%m-%d-%y).md

      # - name: Run script for bundle image pickup # Once the PR has been merged, the link will be active and available for view.
      #   id: image-pickup
      #   run: |
      #     bash ./scripts/bundle-image-pickup.sh -s

      - name: Add updated log report to README # Once the PR has been merged, the link will be active and available for view.
        run: |
          echo -e "\nGenerated auto update. View log file created: [update-log-$(date +%m-%d-%y)](https://github.com/stolostron/search-v2-operator-bundle/blob/main/.github/logs/update-log-$(date +%m-%d-%y).md)" >> README.md

      # - name: Create pull request for updated bundle image versions
      #   if: steps.image-pickup.outcome == 'success'
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     add-paths: .
      #     body: |
      #       This PR is auto-generated by the Git action [bundle-image-update](https://github.com/stolostron/search-v2-operator-bundle/blob/main/.github/workflows/bundle-image-update.yml).
      #     branch-suffix: short-commit-hash
      #     commit-message: 'Updated bundle image versions within the project'
      #     delete-branch: true
      #     labels: automated-pr
      #     reviewers: dislbenn
      #     signoff: true
      #     title: '[Automated PR][Release-2.7] Updated node modules versions within the project'
      #     token: ${{ secrets.GITHUB_TOKEN }}